Feature
BenMukebo/hello-microverse pull request #1
Opened 2021-08-10 15:30 UTC by BenMukebo

## For this project I have done the following:

- [ ] Create a repository,  
- [ ] Set up linters,
- [ ] Add HTML file, 
- [ ] Add CSS file,   
- [ ] Add a test md file,
- [ ] Add descriptive README file.

2021-08-10 17:03 UTC, barackm requested changes
Hi @BenMukebo , 👋 

You have done an amazing job so far! 👏👏👏
However, there are some issues that you still need to work on to go to the next project. But remember you are almost there 😉  😉 !

# STATUS: Required Changes ♻️

### _Check the comments under the review._ 👇 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-10 17:03 UTC, barackm commented on .gitignore
> +test.md
- [ ] Great job on adding the file test.md to the .gitignone file. however, the file is still visible in the repository, the reason for this is that you created the file and committed it before adding it to the .gitigone file. to undo this you can run this command `git rm --cached test.md`. then you can add and commit. with that the file will not be available in the repository.

2021-08-10 17:03 UTC, barackm commented on .github/workflows/linters.yml
> +name: Linters
- [ ] Great job on adding the linters 👏 . but you have a problem with your linter configuration because it doesn't run, please let's follow [these instructions](https://github.com/microverseinc/linters-config/tree/master/html-css) on how to setup the linters correctly.

2021-08-11 08:23 UTC, tahiry-dev approved these changes
Hello Kasongo Mukebo Ben ! 👋, 

Congratulations! 🎉 , your project is complete!  You have done an amazing job 💪💪.
You can now merge it and move to the next step!, 
 👉keep up the good work

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-11 09:12 UTC, merged